using System;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;
using Microsoft.CodeAnalysis;

namespace LfSync.LcmModelGenerator
{

    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Console.Out.WriteLine("!! Hi from geneartor");
            // try
            // {
            //     var serializer = new XmlSerializer(typeof(EntireModel));
            //     using (var reader = XmlReader.Create("MasterLCModel.xml"))
            //     {
            //         var shoppingCart = (EntireModel)serializer.Deserialize(reader);
            //     }
            // } catch(Exception e) {

            // }

            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            // Build up the source code
            string source = $@"// <auto-generated/>
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static partial class {mainMethod.ContainingType.Name}
    {{
        static partial void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from2dd '{{name}}'"");
    }}
}}
";
            var typeName = mainMethod.ContainingType.Name;

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}